---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "192.168.3.10"
    vcenter_username: "administrator@vsphere.reca2"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    folder_prefix: "/Datacenter/vm/3.Students/"
    esxi_password: "VMware1!"
    esxi_username: "root"


  tasks: 
    - name: Create a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix + item.sid }}'

        name: '{{ item.vmname }}'
        state: poweredoff
        guest_id: '{{ item.guest_id }}'
        esxi_hostname: "{{ item.host }}"
        hardware:
          num_cpus: '{{ item.cpus }}'
          memory_mb: '{{ item.memory }}'
          scsi: paravirtual
        disk:
        - size_gb: '{{ item.disk_gb }}'
          type: thin
          datastore: '{{ item.store }}'
        networks:
        - name: '{{ item.vnet }}'
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '{{ item.iso }}'
      with_items:
      - { sid: S00, host: esxi-05.vclass.reca2, vnet: S00-Trunk, store: ESXi-05, vmname: "{{ sid + '-Bastion'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: '[ESXi-05]\ISO\TrueNAS-13.0-U4.iso' }
      delegate_to: localhost
      register: deploy_vm
