## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html#ansible-collections-community-vmware-vmware-vm-shell-module

---
- hosts: localhost

  vars_files: ./vars.yaml

  tasks: 
    - name: VyOS Router Configuration
      community.vmware.vmware_vm_shell:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: 'false'
        datacenter: '{{ datacenter_name }}'
        folder: '{{ folder_prefix + student_ID }}'
        vm_id: "{{ student_ID + '-Router' }}"
        vm_id_type: vm_name
        vm_username: 'vyos'
        vm_password: 'vyos'
        vm_shell: /bin/vbash
        vm_shell_cwd: "/tmp"
        vm_shell_args: |-
          -c "source /opt/vyatta/etc/functions/script-template
          configure
          set system login user admin full-name Admin_User
          set system login user admin authentication plaintext-password VMware1!
          set service ssh port 22
          set system ipv6 disable
          
          set interfaces ethernet eth0 address dhcp
          set interfaces ethernet eth0 description Outside
          set interfaces ethernet eth0 ipv6 address no-default-link-local
          set protocols static route 0.0.0.0/0 next-hop 200.200.200.254

          set system name-server 200.200.200.245
          set service ntp server kr.pool.ntp.org
       
          set interfaces ethernet eth1 vif 100 description 'VLAN 100 - Site A Management'
          set interfaces ethernet eth1 vif 100 address 10.10.100.1/24
          set interfaces ethernet eth1 vif 100 ipv6 address no-default-link-local
          
          set interfaces ethernet eth1 vif 101 description 'VLAN 101 - Site A Storage'
          set interfaces ethernet eth1 vif 101 address 10.10.101.1/24
          set interfaces ethernet eth1 vif 101 ipv6 address no-default-link-local

          set interfaces ethernet eth1 vif 102 description 'VLAN 102 - Site A vMotion'
          set interfaces ethernet eth1 vif 102 address 10.10.102.1/24
          set interfaces ethernet eth1 vif 102 ipv6 address no-default-link-local
          
          set interfaces ethernet eth1 vif 103 description 'VLAN 103 - Site A Production'
          set interfaces ethernet eth1 vif 103 address 10.10.103.1/24
          set interfaces ethernet eth1 vif 103 ipv6 address no-default-link-local
          
          set nat source rule 100 outbound-interface eth0
          set nat source rule 100 source address 10.10.100.0/24
          set nat source rule 100 translation address masquerade

          set nat source rule 103 outbound-interface eth0
          set nat source rule 103 source address 10.10.103.0/24
          set nat source rule 103 translation address masquerade

          delete int eth eth0 addr dhcp
          set int eth eth0 addr 200.200.200.110/24

          set int eth eth0 addr 200.200.200.120/24
          set int eth eth0 addr 200.200.200.125/24
          set int eth eth0 addr 200.200.200.170/24

          set interfaces ethernet eth2 vif 120 description DMZ
          set interfaces ethernet eth2 vif 120 address 10.10.120.1/24
          set interfaces ethernet eth2 vif 120 ipv6 address no-default-link-local

          #d-nat
          set nat destination rule 120 destination addr 200.200.200.120
          set nat destination rule 120 inbound-interface eth0
          set nat destination rule 120 translation addr 10.10.120.2


          set nat destination rule 125 destination addr 200.200.200.125
          set nat destination rule 125 inbound-interface eth0
          set nat destination rule 125 translation addr 10.10.120.3


          set nat destination rule 170 destination addr 200.200.200.170
          set nat destination rule 170 inbound-interface eth0
          set nat destination rule 170 translation addr 10.10.100.100


          set nat source rule 120 outbound-interface eth2
          set nat source rule 120 source address 10.10.120.0/24
          set nat source rule 120 translation address masquerade

          commit
          save"
        wait_for_process: True
        timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout
